location /phpmyadmin {
	alias /web/phpmyadmin;
	index index.php index.html index.htm;
	
	location ~ ^/phpmyadmin/(.+\.php)$ {
		include fastcgi_params;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/run/php/php7.3-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param  SCRIPT_FILENAME  $request_filename;
		fastcgi_param  DOCUMENT_ROOT    /web/phpmyadmin;
	}

	location ~* ^/phpmyadmin/(.*)/[^/].+.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt)$ {
		alias /web/phpmyadmin/$1.$2;
	}
}