location /phpmyadmin {
	root /web;
	index index.php index.html index.htm;
	
	location ~ ^/phpmyadmin/(.+\.php)$ {
		include fastcgi_params;
		fastcgi_split_path_info ^(.+?\.php)(/.*)?$;
		fastcgi_pass unix:/run/php/php7.3-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
	}
	
	location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
		expires 7d;
	}
}