location /phpmyadmin/ {
	alias /web/phpmyadmin/;
	index index.php index.htm index.html;
	
	location ~ ^/phpmyadmin/(.+\.php)$ {
		alias /web/phpmyadmin/$1;
		location ~ \.php$ {
			fastcgi_split_path_info ^(.+?\.php)(/.*)?$;
			fastcgi_pass unix:/run/php/php7.3-fpm.sock;
			fastcgi_index index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			include fastcgi_params;
		}
	}

	location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
		alias /web/phpmyadmin/$1;
	}
}