server {
	listen 80;
	listen 443;
	listen [::]:80;
	listen [::]:443;
	
	server_name pin.*.com;
	
	ssl_certificate	 /opt/certs/*.com/fullchain.pem;
	ssl_certificate_key /opt/certs/*.com/privkey.pem;
	
	location / {
		proxy_pass https://www.pinterest.com/;
		proxy_set_header Host www.pinterest.com;
		proxy_set_header Accept-Encoding "";

		sub_filter_once off;
		sub_filter_types *;
		subs_filter 'i.pinimg.com' 'pin.litexo.com/i.pingimg.com';
		subs_filter 's.pinimg.com' 'pin.litexo.com/s.pingimg.com';
	}
}