log-type: Stderr
keys-file: ./keys
udp-address: 0.0.0.0:33445
tcp-addresses:
  - 0.0.0.0:33445
tcp-connections-limit: 512
motd: "{{start_date}} {{uptime}} Tcp: incoming {{tcp_packets_in}}, outgoing {{tcp_packets_out}}, Udp: incoming {{udp_packets_in}}, outgoing {{udp_packets_out}}"
bootstrap-nodes:
  - pk: BEF0CFB37AF874BD17B9A8F9FE64C75521DB95A37D33C5BDB00E9CF58659C04F
    addr: 198.199.98.108:33445
  - pk: A04F5FE1D006871588C8EC163676458C1EC75B20B4A147433D271E1E85DAF839
    addr: 52.53.185.100:33445
threads: auto # or any u16 > 0
lan-discovery: True