server {
	listen 80;
	listen 443;
	listen [::]:80;
	listen [::]:443;
	
	server_name example.com;
	
	ssl_certificate	 /etc/letsencrypt/live/example.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
	
	location / {
		proxy_pass https://fonts.googleapis.com/;
		proxy_set_header Host fonts.googleapis.com;
		proxy_set_header Accept-Encoding "";
		#include conf.d/google-fonts-proxy-common;
	}
}