server {
	listen 80;
	server_name localhost;
	root /web/public;

	access_log  /var/log/nginx/access.log;

	location / {
		index index.php index.html index.htm;
	}

	error_page  404              /404.html;

	include conf.d/phpmyadmin.conf;
	include conf.d/fastcgi_php.conf;
}